# Netlify Configuration for OrganiTrafficBoost

[build]
  # Build command
  command = "npm run build"
  
  # Output directory (where Vite builds to)
  publish = "dist"
  
  # Node version
  environment = { NODE_VERSION = "18" }

# Production context (main branch)
[context.production]
  command = "npm run build"
  publish = "dist"

# Development context (dev branch)
[context.dev]
  command = "npm run build"
  publish = "dist"

# Branch deploy context (all other branches)
[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

# Deploy previews (pull requests)
[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

# Redirect rules for SPA (Single Page Application)
# This ensures all routes are handled by your React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
