-- Migration to add missing is_active column to user_sessions table
-- Generated by Drizzle Kit

-- Check if the column exists before adding it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'user_sessions' 
        AND column_name = 'is_active'
    ) THEN
        ALTER TABLE user_sessions ADD COLUMN is_active BOOLEAN DEFAULT true;
    END IF;
END $$;

-- Update any existing records to have is_active = true
UPDATE user_sessions SET is_active = true WHERE is_active IS NULL;